version: 2.1

jobs:
  code-climate:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L \
              https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > \
              ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run specs
          command: |
            ./cc-test-reporter before-build
            rake coverage
            ./cc-test-reporter after-build --exit-code $?

workflows:
  version: 2
  build:
    jobs:
      - code-climate
